# Generated by Django 4.1.4 on 2022-12-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcTvProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('details', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.brand')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.catagory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.size')),
            ],
        ),
    ]
