# Generated by Django 4.1.4 on 2022-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cctvproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvproduct',
            name='img',
            field=models.ImageField(default='img', upload_to='productimg'),
            preserve_default=False,
        ),
    ]
