# Generated by Django 4.1.4 on 2022-12-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_cctvproduct_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.CharField(max_length=50)),
            ],
        ),
    ]
