# Generated by Django 4.1.4 on 2023-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_placeorder_status_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('on the way', 'on the way'), ('packed', 'packed'), ('delivered ', 'delivered'), ('cancel ', 'cancel')], default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
