# Generated by Django 4.1.4 on 2023-01-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_placeorder_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(choices=[('cancel ', 'cancel'), ('packed', 'packed'), ('delivered ', 'delivered'), ('accepted', 'accepted'), ('on the way', 'on the way')], default='Pending', max_length=50),
        ),
    ]
