# Generated by Django 4.1.4 on 2023-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_placeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('packed', 'packed'), ('delivered ', 'delivered'), ('cancel ', 'cancel'), ('on the way', 'on the way')], default='Pending', max_length=50),
        ),
    ]
