# Generated by Django 4.1.4 on 2023-01-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_placeorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='status',
            field=models.CharField(choices=[('delivered ', 'delivered'), ('packed', 'packed'), ('accepted', 'accepted'), ('on the way', 'on the way'), ('cancel ', 'cancel')], default='Pending', max_length=50),
        ),
    ]
