# Generated by Django 4.1.4 on 2023-01-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_placeorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='productStatus',
            field=models.CharField(choices=[('delivered ', 'delivered'), ('packed', 'packed'), ('on the way', 'on the way'), ('cancel ', 'cancel'), ('accepted', 'accepted')], default='Pending', max_length=50),
        ),
    ]
