# Generated by Django 4.1.4 on 2023-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_placeorder_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='productStatus',
            field=models.CharField(choices=[('packed', 'packed'), ('on the way', 'on the way'), ('delivered ', 'delivered'), ('accepted', 'accepted')], default='Pending', max_length=50),
        ),
    ]
